dist: trusty
sudo: false
language: python

cache: pip

env:
  - TESTS_TO_RUN=tests/advanced_tests/automated_tests_regressors.py
  - TESTS_TO_RUN=tests/advanced_tests/automated_tests_classifiers.py
  - TESTS_TO_RUN=tests/advanced_tests/advanced_install_tests.py

  - TESTS_TO_RUN=tests/core_tests/api_coverage_tests_classifiers.py
  - TESTS_TO_RUN=tests/core_tests/api_coverage_tests_regressors.py
  - TESTS_TO_RUN=tests/core_tests/basic_tests.py
  - TESTS_TO_RUN=tests/core_tests/calibrate_classifier_tests.py
  - TESTS_TO_RUN=tests/core_tests/categorical_ensembling_test.py
  - TESTS_TO_RUN=tests/core_tests/scoring_tests.py
  - TESTS_TO_RUN=tests/core_tests/test_prediction_intervals.py
  - TESTS_TO_RUN=tests/core_tests/trained_transformation_pipeline_tests.py
  - TESTS_TO_RUN=tests/core_tests/uncertainty_tests.py
  - TESTS_TO_RUN=tests/core_tests/user_logging_tests.py

python:
  - "3.6"



install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls nose tables
  - pip install -r requirements.txt
  - if [[ $TESTS_TO_RUN == *'advanced_tests'* ]]; then pip install lightgbm keras==2.1.1 tensorflow==1.4.0 catboost xgboost; fi
  - if [[ $TESTS_TO_RUN == *'backwards_compatibility_test'* ]]; then pip install scikit-learn==0.18.0; fi

script:
  - nosetests $TESTS_TO_RUN
  - coveralls
