dist: trusty
sudo: false
language: python

cache: pip

#env:
#  - CORE_TESTS=tests/core_tests/scoring_tests.py
#  - ADVANCED_TESTS=tests/core_tests/basic_tests.py
#  - CORE_TESTS=tests/core_tests/api_coverage_tests_classifiers.py
#  - CORE_TESTS=tests/core_tests/api_coverage_tests_regressors.py
#  - CORE_TESTS=tests/core_tests/calibrate_classifier_tests.py
#  - CORE_TESTS=tests/core_tests/categorical_ensembling_test.py
#  - CORE_TESTS=tests/core_tests/test_prediction_intervals.py
#  - CORE_TESTS=tests/core_tests/trained_transformation_pipeline_tests.py
#  - CORE_TESTS=tests/core_tests/uncertainty_tests.py
#  - CORE_TESTS=tests/core_tests/user_logging_tests.py
#  - ADVANCED_TESTS=tests/advanced_tests/automated_tests_regressors.py
#  - ADVANCED_TESTS=tests/advanced_tests/automated_tests_classifiers.py
#  - ADVANCED_TESTS=tests/advanced_tests/advanced_install_tests.py

before_install: # Code coverage for codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
#  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coverage coveralls nose tables
  - pip install -r requirements.txt


jobs:
  include:
    - stage: Core Tests
      python:
        - "3.5"
        - "3.6"
      env:
        - CORE_TESTS=tests/core_tests/scoring_tests.py
      script:
        - nosetests $CORE_TESTS
        - coveralls
        - coverage xml
        - ./cc-test-reporter format-coverage

    - stage: Advanced tests
      python:
        - "3.5"
        - "3.6"
      env:
        - ADVANCED_TESTS=tests/core_tests/basic_tests.py
      install:
        - pip install lightgbm keras tensorflow catboost xgboost
      script:
        - nosetests $ADVANCED_TESTS
        - coveralls
        - coverage xml
        - ./cc-test-reporter format-coverage

    - stage: Upload to Code Climate
      python:
        - 3.6
      script:
        - ./cc-test-reporter sum-coverage
        - ./cc-test-reporter upload-coverage  # Upload coverage