dist: trusty
sudo: false
language: python

cache: pip

before_install: # Code coverage for codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

jobs:
  include:
    - stage: Core Tests
      python:
        - 3.6
      install:
        - pip install --upgrade pip setuptools wheel
        - pip install coverage coveralls nose tables
        - pip install -r requirements.txt
      script:
        - nosetests tests/core_tests
        - coveralls
        - coverage json
        - ./cc-test-reporter format-coverage

    - stage: Advanced tests
      python:
        - 3.6
      install:
        - pip install --upgrade pip setuptools wheel
        - pip install coverage coveralls nose tables
        - pip install -r requirements.txt
        - pip install lightgbm keras tensorflow catboost xgboost
      script:
        - nosetests tests/advanced_tests
        - coveralls
        - coverage json
        - ./cc-test-reporter format-coverage
    - stage: Upload to Code Climate
      python:
        - 3.6
      script:
        - ./cc-test-reporter sum-coverage
        - ./cc-test-reporter upload-coverage  # Upload coverage