dist: trusty
sudo: false
language: python

cache: pip

env:
#  - TESTS_TO_RUN=tests/advanced_tests/automated_tests_regressors.py
#  - TESTS_TO_RUN=tests/advanced_tests/automated_tests_classifiers.py
#  - TESTS_TO_RUN=tests/advanced_tests/advanced_install_tests.py
  - TESTS_TO_RUN=tests/core_tests/api_coverage_tests_classifiers.py
  - TESTS_TO_RUN=tests/core_tests/api_coverage_tests_regressors.py
  - TESTS_TO_RUN=tests/core_tests/basic_tests.py
  - TESTS_TO_RUN=tests/core_tests/calibrate_classifier_tests.py
  - TESTS_TO_RUN=tests/core_tests/categorical_ensembling_test.py
  - TESTS_TO_RUN=tests/core_tests/scoring_tests.py
  - TESTS_TO_RUN=tests/core_tests/test_prediction_intervals.py
  - TESTS_TO_RUN=tests/core_tests/trained_transformation_pipeline_tests.py
  - TESTS_TO_RUN=tests/core_tests/uncertainty_tests.py
  - TESTS_TO_RUN=tests/core_tests/user_logging_tests.py

python:
  - "3.6"
  - "3.5"

before_install: # Code coverage for codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coverage coveralls nose tables
  - pip install -r requirements.txt
  - if [[ $TESTS_TO_RUN == *'advanced_tests'* ]]; then pip install lightgbm keras tensorflow catboost xgboost; fi

jobs:
  include:
    - stage: Run Tests
      script:
        - nosetests $TESTS_TO_RUN
        - coveralls
        - coverage xml
        - ./cc-test-reporter format-coverage
    - stage: Upload to Code Climate
      script:
        - ./cc-test-reporter sum-coverage
        - ./cc-test-reporter upload-coverage  # Upload coverage